### ISSUE TITLE
[Bug] ValueError: need at least one array to concatenate

### ISSUE THREAD

**Issue by Xingjie-Han** [zcablii/LSKNet#47]
### Prerequisite

- [X] I have searched [Issues](https://github.com/open-mmlab/mmrotate/issues) and [Discussions](https://github.com/open-mmlab/mmrotate/discussions) but cannot get the expected help.
- [X] I have read the [FAQ documentation](https://mmrotate.readthedocs.io/en/1.x/notes/4_faq.html) but cannot get the expected help.
- [X] The bug has not been fixed in the [latest version (master)](https://github.com/open-mmlab/mmrotate) or [latest version (1.x)](https://github.com/open-mmlab/mmrotate/tree/dev-1.x).

### Task

I have modified the scripts/configs, or I'm working on my own tasks/models/datasets.

### Branch

master branch https://github.com/open-mmlab/mmrotate

### Environment

TorchVision: 0.14.1+cu116
OpenCV: 4.9.0
MMCV: 1.7.1
MMCV Compiler: GCC 9.3
MMCV CUDA Compiler: 11.6
MMRotate: 0.3.4+

### Reproduces the problem - code sample

When I run train.py on my own datasets, it got an error ValueError: need at least one array to concatenate

### Reproduces the problem - command or script

 python tools/train.py configs/lsknet/lsk_s_fpn_1x_dota_le90.py --gpu-ids 2

### Reproduces the problem - error message

Traceback (most recent call last):
  File "/data/hxj/LSKNet-main/tools/train.py", line 193, in <module>
    main()
  File "/data/hxj/LSKNet-main/tools/train.py", line 182, in main
    train_detector(
  File "/data/hxj/LSKNet-main/mmrotate/apis/train.py", line 141, in train_detector
    runner.run(data_loaders, cfg.workflow)
  File "/home/hxj/anaconda3/envs/openmmlab/lib/python3.9/site-packages/mmcv/runner/epoch_based_runner.py", line 136, in run
    epoch_runner(data_loaders[i], **kwargs)
  File "/home/hxj/anaconda3/envs/openmmlab/lib/python3.9/site-packages/mmcv/runner/epoch_based_runner.py", line 49, in train
    for i, data_batch in enumerate(self.data_loader):
  File "/home/hxj/anaconda3/envs/openmmlab/lib/python3.9/site-packages/torch/utils/data/dataloader.py", line 435, in __iter__
    return self._get_iterator()
  File "/home/hxj/anaconda3/envs/openmmlab/lib/python3.9/site-packages/torch/utils/data/dataloader.py", line 381, in _get_iterator
    return _MultiProcessingDataLoaderIter(self)
  File "/home/hxj/anaconda3/envs/openmmlab/lib/python3.9/site-packages/torch/utils/data/dataloader.py", line 1072, in __init__
    self._reset(loader, first_iter=True)
  File "/home/hxj/anaconda3/envs/openmmlab/lib/python3.9/site-packages/torch/utils/data/dataloader.py", line 1105, in _reset
    self._try_put_index()
  File "/home/hxj/anaconda3/envs/openmmlab/lib/python3.9/site-packages/torch/utils/data/dataloader.py", line 1339, in _try_put_index
    index = self._next_index()
  File "/home/hxj/anaconda3/envs/openmmlab/lib/python3.9/site-packages/torch/utils/data/dataloader.py", line 618, in _next_index
    return next(self._sampler_iter)  # may raise StopIteration
  File "/home/hxj/anaconda3/envs/openmmlab/lib/python3.9/site-packages/torch/utils/data/sampler.py", line 254, in __iter__
    for idx in self.sampler:
  File "/home/hxj/anaconda3/envs/openmmlab/lib/python3.9/site-packages/mmdet/datasets/samplers/group_sampler.py", line 36, in __iter__
    indices = np.concatenate(indices)
ValueError: need at least one array to concatenate

**Comment by 3xiaoli33** [comment]
请问您解决了吗？我也是碰到了这个问题

**Comment by Xingjie-Han** [comment]
您的来信已收到。

**Comment by 3xiaoli33** [comment]
好的收到

**Comment by Iamxiaomage** [comment]
您好，我跑了这个代码，也遇到这个问题
请问一下，您解决了吗？ 
如果解决了，麻烦告诉我一下，可以吗？ 谢谢

**Comment by Xingjie-Han** [comment]
您的来信已收到。

**Comment by 3xiaoli33** [comment]
好的收到

**Comment by Iamxiaomage** [comment]
嗯嗯好的，那可以说一下解决办法吗？

**Comment by Vishawjeet-rmsl** [comment]
Hi, I got this problem as well. Can anyone tell me how to fix this as the issue is marked as solved.

**Comment by 3xiaoli33** [comment]
好的收到

**Comment by zcablii** [comment]
> Hi, I got this problem as well. Can anyone tell me how to fix this as the issue is marked as solved.

Please check your dataset folder path.

**Comment by Vishawjeet-rmsl** [comment]
> > Hi, I got this problem as well. Can anyone tell me how to fix this as the issue is marked as solved.
> 
> Please check your dataset folder path.

Hi, I figured it out. 
The issue was that I was using a custom dataset (but in DOTA format), except that in my case the coordinates values were normalized (between 0 and 1). When I de-normalized them by multiplying with Height and Width of the Image, it worked for me.

So, apart from the dataset folder path, things like this might also be causing similar issue for people.
