### ISSUE TITLE
Default process group has not been initialized, please make sure to call init_process_group.

### ISSUE THREAD

**Issue by fancy-girl** [zcablii/LSKNet#54]
### Prerequisite

- [X] I have searched [Issues](https://github.com/open-mmlab/mmrotate/issues) and [Discussions](https://github.com/open-mmlab/mmrotate/discussions) but cannot get the expected help.
- [X] I have read the [FAQ documentation](https://mmrotate.readthedocs.io/en/1.x/notes/4_faq.html) but cannot get the expected help.
- [X] The bug has not been fixed in the [latest version (master)](https://github.com/open-mmlab/mmrotate) or [latest version (1.x)](https://github.com/open-mmlab/mmrotate/tree/dev-1.x).

### Task

I have modified the scripts/configs, or I'm working on my own tasks/models/datasets.

### Branch

master branch https://github.com/open-mmlab/mmrotate

### Environment

I usually debug on AutoDL-TMP, running code on the server of the laboratory, is a single card GPU.

### Reproduces the problem - code sample

![image](https://github.com/zcablii/LSKNet/assets/28773253/6ed64fe3-c3a9-4203-80cb-1b8ea45a357e)
Hello author, thank you very much for your LSKNet. I used LSKNet in the sub -field of image retrieval -cross view geolocation. I use the weight file of LSK_S_BACKBONE-E9D2E551.pth.

### Reproduces the problem - command or script

 When running the train.py file, the error is reported as shown above. I modified it according to the post on the CSDN.
![image](https://github.com/zcablii/LSKNet/assets/28773253/f11b4645-b0eb-429c-8e66-d27deb307cf4)
I made these modifications in Batchnorm.py and successfully run the train.py file. At present, the effect is considerable. But when I run test.py, I reported an error. The server socket has failed to listen on any local network address. Even if I modify the port in Batchnorm, it is still not possible
![image](https://github.com/zcablii/LSKNet/assets/28773253/2d2c59fe-4a3b-48d0-a2bd-f0758d8d88af)
Can you give me some suggestions? Now I ca n’t find a solution, will I report an error at the beginning of the default process group has not ben initialized.

### Reproduces the problem - error message

第一个报错Traceback (most recent call last):
  File "/root/autodl-tmp/LSK_CVGL/train.py", line 194, in train_model
    outputs, outputs2 = model(inputs, inputs3)  # satellite and drone
  File "/root/miniconda3/envs/xhy/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1110, in _call_impl
    return forward_call(*input, **kwargs)
  File "/root/autodl-tmp/LSK_CVGL/models/model.py", line 13, in forward
    y1 = self.model_1(x1)
  File "/root/miniconda3/envs/xhy/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1110, in _call_impl
    return forward_call(*input, **kwargs)
  File "/root/autodl-tmp/LSK_CVGL/models/LSKnet/make_model.py", line 193, in forward
    part_features = self.lsk(x)
  File "/root/miniconda3/envs/xhy/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1110, in _call_impl
    return forward_call(*input, **kwargs)
  File "/root/autodl-tmp/LSK_CVGL/models/LSKnet/backbones/lsknet/lsknet.py", line 359, in forward
    x = self.forward_features(x)
  File "/root/autodl-tmp/LSK_CVGL/models/LSKnet/backbones/lsknet/lsknet.py", line 349, in forward_features
    x, H, W = patch_embed(x)
  File "/root/miniconda3/envs/xhy/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1110, in _call_impl
    return forward_call(*input, **kwargs)
  File "/root/autodl-tmp/LSK_CVGL/models/LSKnet/backbones/lsknet/lsknet.py", line 225, in forward
    x = self.norm(x)
  File "/root/miniconda3/envs/xhy/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1110, in _call_impl
python-BaseException
    return forward_call(*input, **kwargs)
  File "/root/miniconda3/envs/xhy/lib/python3.8/site-packages/torch/nn/modules/batchnorm.py", line 731, in forward
    world_size = torch.distributed.get_world_size(process_group)
  File "/root/miniconda3/envs/xhy/lib/python3.8/site-packages/torch/distributed/distributed_c10d.py", line 867, in get_world_size
    return _get_group_size(group)
  File "/root/miniconda3/envs/xhy/lib/python3.8/site-packages/torch/distributed/distributed_c10d.py", line 325, in _get_group_size
    default_pg = _get_default_group()
  File "/root/miniconda3/envs/xhy/lib/python3.8/site-packages/torch/distributed/distributed_c10d.py", line 429, in _get_default_group
    raise RuntimeError(
RuntimeError: Default process group has not been initialized, please make sure to call init_process_group.
第二个报错Load the model from ./model/convnext_tri/net_162.pth
3 -> 1:
100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 4732/4732 [06:19<00:00, 12.47it/s]
100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 119/119 [00:07<00:00, 15.51it/s]
Test complete in 6m 27s
[W socket.cpp:426] [c10d] The server socket has failed to bind to [::]:40411 (errno: 98 - Address already in use).
[W socket.cpp:426] [c10d] The server socket has failed to bind to 0.0.0.0:40411 (errno: 98 - Address already in use).
[E socket.cpp:462] [c10d] The server socket has failed to listen on any local network address.
Traceback (most recent call last):
  File "evaluate.py", line 2, in <module>
    import torch
  File "/home/ubuntu/anaconda3/envs/xhypy3.7/lib/python3.7/site-packages/torch/__init__.py", line 805, in <module>
    from .functional import *  # noqa: F403
  File "/home/ubuntu/anaconda3/envs/xhypy3.7/lib/python3.7/site-packages/torch/functional.py", line 8, in <module>
    import torch.nn.functional as F
  File "/home/ubuntu/anaconda3/envs/xhypy3.7/lib/python3.7/site-packages/torch/nn/__init__.py", line 1, in <module>
    from .modules import *  # noqa: F403
  File "/home/ubuntu/anaconda3/envs/xhypy3.7/lib/python3.7/site-packages/torch/nn/modules/__init__.py", line 18, in <module>
    from .batchnorm import BatchNorm1d, BatchNorm2d, BatchNorm3d, SyncBatchNorm, \
  File "/home/ubuntu/anaconda3/envs/xhypy3.7/lib/python3.7/site-packages/torch/nn/modules/batchnorm.py", line 28, in <module>
    dist.init_process_group(backend=backend, init_method=init_method, world_size=world_size, rank=rank)
  File "/home/ubuntu/anaconda3/envs/xhypy3.7/lib/python3.7/site-packages/torch/distributed/distributed_c10d.py", line 754, in init_process_group
    store, rank, world_size = next(rendezvous_iterator)
  File "/home/ubuntu/anaconda3/envs/xhypy3.7/lib/python3.7/site-packages/torch/distributed/rendezvous.py", line 246, in _env_rendezvous_handler
    store = _create_c10d_store(master_addr, master_port, rank, world_size, timeout)
  File "/home/ubuntu/anaconda3/envs/xhypy3.7/lib/python3.7/site-packages/torch/distributed/rendezvous.py", line 178, in _create_c10d_store
    hostname, port, world_size, start_daemon, timeout, multi_tenant=True
RuntimeError: The server socket has failed to listen on any local network address. The server socket has failed to bind to [::]:40411 (errno: 98 - Address already in use). The server socket has failed to bind to 0.0.0.0:40411 (errno: 98 - Address already in use).

**Comment by zcablii** [comment]
Try to change 'SyncBN' to 'BN'.

**Comment by fancy-girl** [comment]
Thank you very much. This is very useful. I am running the program again
