### ISSUE TITLE
KeyError: "OrientedRCNN: 'LSKNet is not in the models registry'"

### ISSUE THREAD

**Issue by daihaoma** [zcablii/LSKNet#69]
### What's the feature?

作者你好，我在进行下面操作时python LSKNet-main/tools/train.py LSKNet-main/configs/lsknet/lsk_s_fpn_1x_dota_le90.py --gpu-ids 1 出现错误，内容如下：
Traceback (most recent call last):
  File "LSKNet-main/tools/train.py", line 161, in <module>
    main()
  File "LSKNet-main/tools/train.py", line 131, in main
    model = build_detector(
  File "F:\Anaconda\envs\openmmlab\lib\site-packages\mmrotate\models\builder.py", line 55, in build_detector
    return ROTATED_DETECTORS.build(
  File "F:\Anaconda\envs\openmmlab\lib\site-packages\mmcv\utils\registry.py", line 237, in build
    return self.build_func(*args, **kwargs, registry=self)
  File "F:\Anaconda\envs\openmmlab\lib\site-packages\mmcv\cnn\builder.py", line 27, in build_model_from_cfg
    return build_from_cfg(cfg, registry, default_args)
  File "F:\Anaconda\envs\openmmlab\lib\site-packages\mmcv\utils\registry.py", line 72, in build_from_cfg
    raise type(e)(f'{obj_cls.__name__}: {e}')
KeyError: "OrientedRCNN: 'LSKNet is not in the models registry'"
附上我的log
[20240614_165203.log](https://github.com/user-attachments/files/15836505/20240614_165203.log)

**Comment by zcablii** [comment]
refer to #8

**Comment by daihaoma** [comment]
> 参考#8

感谢
